# -*- coding: utf-8 -*-
"""gsplat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbINu5-NxYFK3RWkXvtRNa39wJwCWxi4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat << 'EOF' > /content/config.sh
# #!/bin/bash
# 
# export ROOTDIR="/content/work"
# export VIDEOSOURCE="gsplat/input/IMG_4765.MOV"
# export IMAGESET="gsplat/input/perfume/images"
# export INPUT_MODE="images"
# 
# export FPS=25
# #export PROFILE="gpu/quality"
# export PROFILE="gpu/balanced"
# #export PROFILE="cpu/fast"
# EOF

!cat /content/config.sh

from google.colab import drive
drive.mount('/content/drive')

!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda
!/usr/local/miniconda/bin/conda init bash

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# source /content/config.sh
# 
# mkdir -p "$ROOTDIR"
# 
# if [ -n "$VIDEOSOURCE" ]; then
#   SRC_VIDEO="/content/drive/MyDrive/$VIDEOSOURCE"
# 
#   if [ ! -f "$SRC_VIDEO" ]; then
#     echo "❌ Video not found: $SRC_VIDEO"
#   else
#     echo "🎬 Copying video: $SRC_VIDEO"
#     cp -f "$SRC_VIDEO" "$ROOTDIR/video.mp4"
#   fi
# fi
# 
# if [ -n "$IMAGESET" ]; then
#   SRC_IMAGES="/content/drive/MyDrive/$IMAGESET"
#   DST_IMAGES="$ROOTDIR/images"
# 
#   if [ ! -d "$SRC_IMAGES" ]; then
#     echo "❌ Image dataset not found: $SRC_IMAGES"
#   else
#     echo "🖼️ Preparing image dataset: $SRC_IMAGES"
# 
#     mkdir -p "$DST_IMAGES"
# 
#     COUNT=$(find "$SRC_IMAGES" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | wc -l | tr -d ' ')
#     if [ "$COUNT" -lt 2 ]; then
#       echo "❌ Not enough images ($COUNT)"
#       exit 1
#     fi
# 
#     rm -f "$DST_IMAGES"/frame_*.png 2>/dev/null || true
# 
#     i=1
#     for img in $(find "$SRC_IMAGES" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | sort); do
#       printf -v idx "%05d" "$i"
#       cp "$img" "$DST_IMAGES/frame_${idx}.png"
#       i=$((i+1))
#     done
# 
#     echo "✅ Dataset ready in $DST_IMAGES"
#   fi
# fi

rm -rf /content/images

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NicoIGN/video_to_ply.git
# %cd video_to_ply

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/video_to_ply
# git stash save && git checkout dev && git pull

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# source /usr/local/miniconda/etc/profile.d/conda.sh
# conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
# conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
# 
# 
# #conda env update -n gsplat -f environment/conda_colab.yml --prune
# conda env create -n gsplat -f environment/conda_colab.yml
#

!source /usr/local/miniconda/etc/profile.d/conda.sh && \
source /content/config.sh && \
echo INPUT_MODE=$INPUT_MODE && \
cd /content/video_to_ply/ && \
conda activate gsplat && \
INPUT_ARG="" && \
if [ "$INPUT_MODE" = "images" ] && [ -n "$IMAGESET" ]; then \
  INPUT_ARG="--images $ROOTDIR/images"; \
elif [ "$INPUT_MODE" = "video" ] && [ -n "$VIDEOSOURCE" ]; then \
  INPUT_ARG="--video $ROOTDIR/video.mp4 --fps $FPS"; \
fi && \
bash run.sh $INPUT_ARG --root "$ROOTDIR" --skip-conda --profile "$PROFILE" --no-proxy

!source /usr/local/miniconda/etc/profile.d/conda.sh && \
source /content/config.sh && \
echo "skipping all except exporting step" && \
cd /content/video_to_ply/ && \
conda activate gsplat && \
INPUT_ARG="" && \
if [ "$INPUT_MODE" = "images" ] && [ -n "$IMAGESET" ]; then \
  INPUT_ARG="--images $ROOTDIR/images"; \
elif [ "$INPUT_MODE" = "video" ] && [ -n "$VIDEOSOURCE" ]; then \
  INPUT_ARG="--video $ROOTDIR/video.mp4 --fps $FPS"; \
fi && \
bash run.sh $INPUT_ARG --root "$ROOTDIR" --skip-conda --profile "$PROFILE" --no-proxy --skip-conda --skip-frame-extraction --skip-colmap  --skip-training

from google.colab import files
import os
import subprocess
import glob

# =========================
# LOAD CONFIG.SH VARIABLES
# =========================
result = subprocess.run(
    "source /content/config.sh && env",
    shell=True,
    executable="/bin/bash",
    capture_output=True,
    text=True,
)

for line in result.stdout.splitlines():
    if "=" in line:
        key, value = line.split("=", 1)
        os.environ[key] = value

# =========================
# FIND ALL PLY FILES
# =========================
rootdir = os.environ.get("ROOTDIR", "/content/work")
export_dir = os.path.join(rootdir, "exports")

ply_files = sorted(
    glob.glob(os.path.join(export_dir, "*.ply"))
)

if not ply_files:
    print("⚠️ No PLY files found.")
    print(f"📂 Searched in: {export_dir}")
else:
    print(f"📦 Found {len(ply_files)} PLY file(s):")

    for ply_path in ply_files:
        print(f"⬇️ Downloading: {os.path.basename(ply_path)}")
        files.download(ply_path)