# -*- coding: utf-8 -*-
"""gsplat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbINu5-NxYFK3RWkXvtRNa39wJwCWxi4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat << 'EOF' > /content/config.sh
# #!/bin/bash
# 
# export ROOTDIR="/content/work"
# export VIDEOSOURCE="gsplat/input/IMG_4770.MOV"
# export FPS=4
# export PROFILE="gpu/fast"
# export PROFILE="cpu/fast"
# EOF

!cat /content/config.sh

!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!chmod +x Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda
!/usr/local/miniconda/bin/conda init bash

from google.colab import drive
drive.mount('/content/drive')

!source /content/config.sh && \
mkdir -p $ROOTDIR && \
cp /content/drive/MyDrive/$VIDEOSOURCE $ROOTDIR/video.mp4 && \
ls $ROOTDIR/

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NicoIGN/video_to_ply.git
# %cd video_to_ply

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/video_to_ply
# git checkout dev && git pull

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# source /usr/local/miniconda/etc/profile.d/conda.sh
# conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
# conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
# 
# 
# #conda env update -n gsplat -f environment/conda_colab.yml --prune
# conda env create -n gsplat -f environment/conda_colab.yml
#

!source /usr/local/miniconda/etc/profile.d/conda.sh && source /content/config.sh && cd /content/video_to_ply/ && conda activate gsplat && bash run.sh --video $ROOTDIR/video.mp4 --root $ROOTDIR --fps $FPS --skip-conda --profile $PROFILE --no-proxy

!source /usr/local/miniconda/etc/profile.d/conda.sh && source /content/config.sh && cd /content/video_to_ply/ && conda activate gsplat && bash run.sh --video $ROOTDIR/video.mp4 --root $ROOTDIR --skip-conda --skip-frame-extraction --skip-colmap  --skip-training --profile $PROFILE --no-proxy

from google.colab import files
import os
import subprocess
import glob

# Load config.sh
result = subprocess.run(
    "source /content/config.sh && env",
    shell=True,
    executable="/bin/bash",
    capture_output=True,
    text=True,
)

for line in result.stdout.splitlines():
    if "=" in line:
        key, value = line.split("=", 1)
        os.environ[key] = value

# Find first PLY
rootdir = os.environ.get("ROOTDIR", "/content/work")
ply_files = glob.glob(os.path.join(rootdir, "exports", "*.ply"))

if ply_files:
    ply_path = ply_files[0]
    print(f"✅ Downloading: {ply_path}")
    files.download(ply_path)
else:
    print("⚠️ No PLY file found in exports directory.")
    print(f"📂 Searched in: {os.path.join(rootdir, 'exports')}")