# -*- coding: utf-8 -*-
"""gsplat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbINu5-NxYFK3RWkXvtRNa39wJwCWxi4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat << 'EOF' > /content/config.sh
# #!/bin/bash
# 
# export ROOTDIR="/content/exterieur"
# export VIDEOSOURCE="gsplat/input/IMG_4797.MOV"
# export IMAGESET="gsplat/input/perfume/video"
# export INPUT_MODE="video"
# 
# #export NUM_FRAMES=150
# export FPS=3
# 
# #branche dev
# export GIT_BRANCH="dev"
# export BASENAME="exterieur"
# 
# export PROFILE="gpu/quality"
# #export PROFILE="gpu/balanced"
# #export PROFILE="cpu/fast"
# EOF

!cat /content/config.sh

from google.colab import drive
drive.mount('/content/drive')

!wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
!bash Miniforge3-Linux-x86_64.sh -b -p /usr/local/miniforge

# activer conda pour cette session notebook
import os
os.environ["PATH"] = "/usr/local/miniforge/bin:" + os.environ["PATH"]

!conda --version

!RUN=0; \
[ "$RUN" -eq 0 ] && echo "skipping this stage" || \
(wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
chmod +x Miniconda3-latest-Linux-x86_64.sh  && \
bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda  && \
/usr/local/miniconda/bin/conda init bash)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# source /content/config.sh
# 
# mkdir -p "$ROOTDIR"
# 
# if [ -n "$VIDEOSOURCE" ]; then
#   SRC_VIDEO="/content/drive/MyDrive/$VIDEOSOURCE"
# 
#   if [ ! -f "$SRC_VIDEO" ]; then
#     echo "❌ Video not found: $SRC_VIDEO"
#   else
#     echo "🎬 Copying video: $SRC_VIDEO"
#     cp -f "$SRC_VIDEO" "$ROOTDIR/video.mp4"
#   fi
# fi
# 
# if [ -n "$IMAGESET" ]; then
#   SRC_IMAGES="/content/drive/MyDrive/$IMAGESET"
#   DST_IMAGES="$ROOTDIR/images"
# 
#   if [ ! -d "$SRC_IMAGES" ]; then
#     echo "❌ Image dataset not found: $SRC_IMAGES"
#   else
#     echo "🖼️ Preparing image dataset: $SRC_IMAGES"
# 
#     mkdir -p "$DST_IMAGES"
# 
#     COUNT=$(find "$SRC_IMAGES" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | wc -l | tr -d ' ')
#     if [ "$COUNT" -lt 2 ]; then
#       echo "❌ Not enough images ($COUNT)"
#       exit 1
#     fi
# 
#     rm -f "$DST_IMAGES"/frame_*.png 2>/dev/null || true
# 
#     i=1
#     for img in $(find "$SRC_IMAGES" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | sort); do
#       printf -v idx "%05d" "$i"
#       cp "$img" "$DST_IMAGES/frame_${idx}.png"
#       i=$((i+1))
#     done
# 
#     echo "✅ Dataset ready in $DST_IMAGES"
#   fi
# fi

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NicoIGN/video_to_ply.git
# %cd video_to_ply

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/video_to_ply
# source /content/config.sh
# git stash save && git checkout $GIT_BRANCH && git pull

!RUN=0; \
[ "$RUN" -eq 0 ] && echo "skipping this stage" || \
( source /usr/local/miniforge/etc/profile.d/conda.sh && mamba env remove -y -n gsplat )

!source /usr/local/miniforge/etc/profile.d/conda.sh && \
mamba env list | grep -q "gsplat" && \
mamba env update -n gsplat -f environment/conda_colab.yml --prune -y || \
mamba env create -n gsplat -f environment/conda_colab.yml -y

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# source /usr/local/miniforge/etc/profile.d/conda.sh
# 
# SITE_PACKAGES=$(mamba run -n gsplat python -c "import site; print(site.getsitepackages()[0])")
# TARGET="$SITE_PACKAGES/SuperGluePretrainedNetwork"
# 
# if [ ! -d "$TARGET" ]; then
#     git clone --depth 1 \
#         https://github.com/magicleap/SuperGluePretrainedNetwork.git \
#         "$TARGET"
# else
#     echo "SuperGluePretrainedNetwork already installed."
# fi

!source /usr/local/miniforge/etc/profile.d/conda.sh && \
mamba run -n gsplat python -c "from SuperGluePretrainedNetwork.models import superpoint; print('SuperGluePretrainedNetwork OK')"

!source /usr/local/miniforge/etc/profile.d/conda.sh && \
source /content/config.sh && unset NUM_FRAMES && \
echo INPUT_MODE=$INPUT_MODE && \
cd /content/video_to_ply/ && \
INPUT_ARG="" && \
if [ "$INPUT_MODE" = "images" ] && [ -n "$IMAGESET" ]; then \
  INPUT_ARG="--images $ROOTDIR/images --name $BASENAME"; \
elif [ "$INPUT_MODE" = "video" ] && [ -n "$VIDEOSOURCE" ]; then \
  INPUT_ARG="--video $ROOTDIR/video.mp4 --fps $FPS --name $BASENAME"; \
fi && \
mamba run -n gsplat bash run.sh $INPUT_ARG --root "$ROOTDIR" --skip-conda --profile "$PROFILE" --no-proxy

!RUN=0; \
[ "$RUN" -eq 0 ] && echo "skipping this stage" || \
( source /usr/local/miniforge/etc/profile.d/conda.sh && \
  source /content/config.sh && \
  cd /content/video_to_ply/ && \
  INPUT_ARG="" && \
  if [ "$INPUT_MODE" = "images" ] && [ -n "$IMAGESET" ]; then \
    INPUT_ARG="--images $ROOTDIR/images --name $BASENAME"; \
  elif [ "$INPUT_MODE" = "video" ] && [ -n "$VIDEOSOURCE" ]; then \
    INPUT_ARG="--video $ROOTDIR/video.mp4 --name $BASENAME"; \
  fi && \
  mamba run -n gsplat bash run.sh $INPUT_ARG \
    --root "$ROOTDIR" \
    --skip-conda \
    --profile "$PROFILE" \
    --no-proxy \
    --skip-conda \
    --skip-frame-extraction \
    --skip-colmap \
    --skip-training )

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# source /content/config.sh
# cd $ROOTDIR/ori
# zip -r $ROOTDIR/exports/colmap_$BASENAME.zip ./colmap

from google.colab import files
import os
import subprocess

# =========================
# LOAD CONFIG.SH VARIABLES
# =========================
result = subprocess.run(
    "source /content/config.sh && env",
    shell=True,
    executable="/bin/bash",
    capture_output=True,
    text=True,
)

for line in result.stdout.splitlines():
    if "=" in line:
        key, value = line.split("=", 1)
        os.environ[key] = value

# =========================
# CONFIG
# =========================
rootdir = os.environ.get("ROOTDIR", "/content/work")
export_dir = os.path.join(rootdir, "exports")
basename = os.environ.get("BASENAME", "")

if not basename:
    print("❌ BASENAME is not set")
    raise SystemExit(1)

base_ply = os.path.join(export_dir, f"{basename}.ply")

# =========================
# EXPORT ORIGINAL PLY
# =========================
if os.path.exists(base_ply):
    print(f"⬇️ Downloading original PLY: {os.path.basename(base_ply)}")
    files.download(base_ply)
else:
    print(f"⚠️ Original PLY not found: {base_ply}")

from google.colab import files
import os
import subprocess
import glob

# =========================
# LOAD CONFIG.SH VARIABLES
# =========================
result = subprocess.run(
    "source /content/config.sh && env",
    shell=True,
    executable="/bin/bash",
    capture_output=True,
    text=True,
)

for line in result.stdout.splitlines():
    if "=" in line:
        key, value = line.split("=", 1)
        os.environ[key] = value

# =========================
# CONFIG
# =========================
rootdir = os.environ.get("ROOTDIR", "/content/work")
export_dir = os.path.join(rootdir, "exports")
basename = os.environ.get("BASENAME", "")

if not basename:
    print("❌ BASENAME is not set")
    raise SystemExit(1)

# =========================
# FIND FILTERED PLYS
# =========================
filtered_plys = sorted(
    glob.glob(os.path.join(export_dir, f"{basename}_*.ply"))
)

# =========================
# EXPORT FILTERED PLYS
# =========================
if not filtered_plys:
    print("⚠️ No filtered PLY files found.")
    print(f"📂 Searched: {export_dir}")
else:
    print(f"📦 Found {len(filtered_plys)} filtered PLY file(s)")

    for ply_path in filtered_plys:
        print(f"⬇️ Downloading filtered PLY: {os.path.basename(ply_path)}")
        files.download(ply_path)