# -*- coding: utf-8 -*-
"""gsplat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bbINu5-NxYFK3RWkXvtRNa39wJwCWxi4
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cat << 'EOF' > /content/config.sh
# #!/bin/bash
# 
# export ROOTDIR="/content/statue"
# export VIDEOSOURCE="gsplat/input/IMG_4794.MOV"
# 
# export NUM_FRAMES=100
# 
# #branche dev
# export GIT_BRANCH="dev"
# export BASENAME="sofa"
# 
# export PREPROCESS_PROFILE="hloc-lightblue"
# export GSPLAT_PROFILE="quality_plus"
# 
# EOF
# 
# cat /content/config.sh

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# set -e
# source /content/config.sh
# 
# mkdir -p "$ROOTDIR"
# 
# if [ -n "$VIDEOSOURCE" ]; then
#   SRC_VIDEO="/content/drive/MyDrive/$VIDEOSOURCE"
# 
#   if [ ! -f "$SRC_VIDEO" ]; then
#     echo "❌ Video not found: $SRC_VIDEO"
#   else
#     echo "🎬 Copying video: $SRC_VIDEO"
#     cp -f "$SRC_VIDEO" "$ROOTDIR/video.mp4"
#   fi
# fi

!wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
!bash Miniforge3-Linux-x86_64.sh -b -p /usr/local/miniforge

# activer conda pour cette session notebook
import os
os.environ["PATH"] = "/usr/local/miniforge/bin:" + os.environ["PATH"]

!conda --version

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/NicoIGN/video_to_ply.git
# %cd video_to_ply

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/video_to_ply
# source /content/config.sh
# git stash save && git checkout $GIT_BRANCH && git pull



!source /usr/local/miniforge/etc/profile.d/conda.sh && \
mamba env list | grep -q gsplat && \
cd /content/video_to_ply/ && \
mamba run -n gsplat mamba env update -n gsplat -f environment/conda_colab.yml --prune -y || \
mamba env create -n gsplat -f environment/conda_colab.yml -y

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# source /usr/local/miniforge/etc/profile.d/conda.sh
# 
# SITE_PACKAGES=$(mamba run -n gsplat python -c "import site; print(site.getsitepackages()[0])")
# TARGET="$SITE_PACKAGES/SuperGluePretrainedNetwork"
# 
# if [ ! -d "$TARGET" ]; then
#     git clone --depth 1 \
#         https://github.com/magicleap/SuperGluePretrainedNetwork.git \
#         "$TARGET"
# else
#     echo "SuperGluePretrainedNetwork already installed."
# fi

!RUN=1; \
[ "$RUN" -eq 0 ] && echo "skipping this stage" || \
 (source /usr/local/miniforge/etc/profile.d/conda.sh && \
source /content/config.sh && \
cd /content/video_to_ply/ && \
mamba run -n gsplat bash run.sh  \
--root "$ROOTDIR" \
--name "$BASENAME" \
--video $ROOTDIR/video.mp4  \
--skip-conda \
--skip-filter \
--preprocess-profile "$PREPROCESS_PROFILE" \
--gsplat-profile "$GSPLAT_PROFILE" \
--num-frames $NUM_FRAMES \
--no-proxy)

!RUN=0; \
[ "$RUN" -eq 0 ] && echo "skipping this stage" || \
 (source /usr/local/miniforge/etc/profile.d/conda.sh && \
source /content/config.sh && \
cd /content/video_to_ply/ && \
mamba run -n gsplat bash run.sh  \
--root "$ROOTDIR" \
--name "$BASENAME" \
--video $ROOTDIR/video.mp4  \
--skip-conda \
--skip-filter \
--preprocess-profile "$PREPROCESS_PROFILE" \
--gsplat-profile "$GSPLAT_PROFILE" \
--fps $FPS \
--no-proxy)

from google.colab import files
import os
import subprocess

# =========================
# LOAD CONFIG.SH VARIABLES
# =========================
result = subprocess.run(
    "source /content/config.sh && env",
    shell=True,
    executable="/bin/bash",
    capture_output=True,
    text=True,
)

for line in result.stdout.splitlines():
    if "=" in line:
        key, value = line.split("=", 1)
        os.environ[key] = value

# =========================
# CONFIG
# =========================
rootdir = os.environ.get("ROOTDIR", "/content/work")
export_dir = os.path.join(rootdir, "exports")
basename = os.environ.get("BASENAME", "")

if not basename:
    print("❌ BASENAME is not set")
    raise SystemExit(1)


# =========================
# EXPORT ORIGINAL PLY
# =========================
base_ply = os.path.join(export_dir, f"{basename}.ply")
if os.path.exists(base_ply):
    print(f"⬇️ Downloading original PLY: {os.path.basename(base_ply)}")
    files.download(base_ply)
else:
    print(f"⚠️ Original PLY not found: {base_ply}")

from google.colab import files
import os
import subprocess
import os

# =========================
# LOAD CONFIG.SH VARIABLES
# =========================
result = subprocess.run(
    "source /content/config.sh && env",
    shell=True,
    executable="/bin/bash",
    capture_output=True,
    text=True,
)

for line in result.stdout.splitlines():
    if "=" in line:
        key, value = line.split("=", 1)
        os.environ[key] = value

# =========================
# CONFIG
# =========================
rootdir = os.environ.get("ROOTDIR", "/content/work")
export_dir = os.path.join(rootdir, "exports")
basename = os.environ.get("BASENAME", "")

if not basename:
    print("❌ BASENAME is not set")
    raise SystemExit(1)


# =========================
# EXPORT COLMAP DATA
# =========================
base_zip = os.path.join(export_dir, f"colmap_{basename}.zip")
if os.path.exists(base_zip):
    print(f"⬇️ Downloading original PLY: {os.path.basename(base_zip)}")
    files.download(base_zip)
else:
    print(f"⚠️ COLMAP data not found: {base_zip}")

# =========================
# EXPORT LATEST RUN ZIP
# =========================

zip_files = [
    os.path.join(export_dir, f)
    for f in os.listdir(export_dir)
    if f.endswith(".zip")
]

if not zip_files:
    print(f"⚠️ No zip archives found in: {export_dir}")
else:
    latest_zip = max(zip_files, key=os.path.getmtime)

    print(f"⬇️ Downloading latest run archive: {os.path.basename(latest_zip)}")
    files.download(latest_zip)