name: gsplat

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip

  # Build
  - cmake
  - ninja
  - gcc_linux-64=11
  - gxx_linux-64=11

  # PyTorch CUDA 12.1
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1

  # CUDA COMPONENTS ONLY
  - cuda-nvcc=12.1
  - cuda-cudart-dev=12.1
  - cuda-runtime=12.1

  # Utils
  - numpy<2
  - scipy
  - matplotlib
  - tqdm
  - ffmpeg
  - imageio
  - imageio-ffmpeg
  - plyfile
  - colmap=3.8
  - faiss-cpu

  - pip:
      - nerfstudio==1.1.5
      - fpsample
      - ultralytics
      - git+https://github.com/cvg/Hierarchical-Localization.git
      - git+https://github.com/facebookresearch/segment-anything.git
