name: gsplat

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip

  # Utilities
  - rclone
  - tree
  - tqdm
  - matplotlib

  # Build tools
  - cmake
  - ninja
  - gcc_linux-64=11
  - gxx_linux-64=11

  # PyTorch + CUDA
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - cuda-nvcc=12.1
  - uda-cudart=12.1
  - cuda-compiler=12.1
  - cuda-toolkit=12.1

  # Scientific stack
  - "numpy<2"
  - scipy

  # IO / Media
  - openimageio
  - ffmpeg
  - imageio
  - imageio-ffmpeg

  # Geometry / SfM
  - colmap=3.8
  - faiss-cpu
  - plyfile

  # Graphics
  # - glew
  #- qt-main

  - pip:
      - nerfstudio==1.1.5
      - fpsample
      - ultralytics
      - plyfile
      - git+https://github.com/cvg/Hierarchical-Localization.git
      - git+https://github.com/facebookresearch/segment-anything.git
      - git+https://github.com/nerfstudio-project/gsplat.git@v1.4.0
